In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Titanic.csv')
df.head()

,Pclass,Sex,Age,SibSp,Parch,family,Fare,Cabin,Embarked,Survived
0,3,male,22.0,1,0,1,7.2500,NaN,S,0
1,1,female,38.0,1,0,1,71.2833,C85,C,1
2,3,female,26.0,0,0,0,7.9250,NaN,S,1
3,1,female,35.0,1,0,1,53.1000,C123,S,1
4,3,male,35.0,0,0,0,8.0500,NaN,S,0

In [3]:
df['Age'].fillna (df['Age'].mean(), inplace=True)

In [4]:
df.head()

,Pclass,Sex,Age,SibSp,Parch,family,Fare,Cabin,Embarked,Survived
0,3,male,22.0,1,0,1,7.2500,NaN,S,0
1,1,female,38.0,1,0,1,71.2833,C85,C,1
2,3,female,26.0,0,0,0,7.9250,NaN,S,1
3,1,female,35.0,1,0,1,53.1000,C123,S,1
4,3,male,35.0,0,0,0,8.0500,NaN,S,0

In [5]:
df['Cabin'].fillna(0,inplace=True)

In [6]:
df.head()

,Pclass,Sex,Age,SibSp,Parch,family,Fare,Cabin,Embarked,Survived
0,3,male,22.0,1,0,1,7.2500,0,S,0
1,1,female,38.0,1,0,1,71.2833,C85,C,1
2,3,female,26.0,0,0,0,7.9250,0,S,1
3,1,female,35.0,1,0,1,53.1000,C123,S,1
4,3,male,35.0,0,0,0,8.0500,0,S,0

In [7]:
df['Cabin'] [df['Cabin'] !=0] = 1

In [8]:
df.head()

,Pclass,Sex,Age,SibSp,Parch,family,Fare,Cabin,Embarked,Survived
0,3,male,22.0,1,0,1,7.2500,0,S,0
1,1,female,38.0,1,0,1,71.2833,1,C,1
2,3,female,26.0,0,0,0,7.9250,0,S,1
3,1,female,35.0,1,0,1,53.1000,1,S,1
4,3,male,35.0,0,0,0,8.0500,0,S,0

In [9]:
df= pd.get_dummies(df, columns=['Sex', 'Embarked'], drop_first=True)

In [10]:
df.head()

,Pclass,Age,SibSp,Parch,family,Fare,Cabin,Survived,Sex_male,Embarked_N,Embarked_Q,Embarked_S
0,3,22.0,1,0,1,7.2500,0,0,True,False,False,True
1,1,38.0,1,0,1,71.2833,1,1,False,False,False,False
2,3,26.0,0,0,0,7.9250,0,1,False,False,False,True
3,1,35.0,1,0,1,53.1000,1,1,False,False,False,True
4,3,35.0,0,0,0,8.0500,0,0,True,False,False,True

In [11]:
df['Sex_male'] = df['Sex_male'].astype(int)
df['Embarked_N'] = df['Embarked_N'].astype (int)
df['Embarked_Q'] = df['Embarked_Q'].astype (int)
df['Embarked_S'] = df['Embarked_S'].astype (int)
df.head()

,Pclass,Age,SibSp,Parch,family,Fare,Cabin,Survived,Sex_male,Embarked_N,Embarked_Q,Embarked_S
0,3,22.0,1,0,1,7.2500,0,0,1,0,0,1
1,1,38.0,1,0,1,71.2833,1,1,0,0,0,0
2,3,26.0,0,0,0,7.9250,0,1,0,0,0,1
3,1,35.0,1,0,1,53.1000,1,1,0,0,0,1
4,3,35.0,0,0,0,8.0500,0,0,1,0,0,1

In [12]:
df.corr()

,Pclass,Age,SibSp,Parch,family,Fare,Cabin,Survived,Sex_male,Embarked_N,Embarked_Q,Embarked_S
Pclass,1.000000,-0.331339,0.083081,0.018443,0.065997,-0.549500,-0.725541,-0.338481,0.131900,-0.074282,0.221009,0.081720
Age,-0.331339,1.000000,-0.232625,-0.179191,-0.248512,0.091566,0.233123,-0.069809,0.084153,0.074099,-0.013855,-0.027121
SibSp,0.083081,-0.232625,1.000000,0.414838,0.890712,0.159651,-0.040460,-0.035322,-0.114631,-0.022508,-0.026354,0.070941
Parch,0.018443,-0.179191,0.414838,1.000000,0.783111,0.216225,0.036987,0.081629,-0.245489,-0.022467,-0.081228,0.063036
family,0.065997,-0.248512,0.890712,0.783111,1.000000,0.217138,-0.009175,0.016639,-0.200988,-0.026608,-0.058592,0.079977
Fare,-0.549500,0.091566,0.159651,0.216225,0.217138,1.000000,0.482075,0.257307,-0.182333,0.045646,-0.117216,-0.166603
Cabin,-0.725541,0.233123,-0.040460,0.036987,-0.009175,0.482075,1.000000,0.316912,-0.140391,0.087042,-0.129572,-0.110087
Survived,-0.338481,-0.069809,-0.035322,0.081629,0.016639,0.257307,0.316912,1.000000,-0.543351,0.060095,0.003650,-0.155660
Sex_male,0.131900,0.084153,-0.114631,-0.245489,-0.200988,-0.182333,-0.140391,-0.543351,1.000000,-0.064296,-0.074115,0.125722
Embarked_N,-0.074282,0.074099,-0.022508,-0.022467,-0.026608,0.045646,0.087042,0.060095,-0.064296,1.000000,-0.014588,-0.076588
Embarked_Q,0.221009,-0.013855,-0.026354,-0.081228,-0.058592,-0.117216,-0.129572,0.003650,-0.074115,-0.014588,1.000000,-0.496624
Embarked_S,0.081720,-0.027121,0.070941,0.063036,0.079977,-0.166603,-0.110087,-0.155660,0.125722,-0.076588,-0.496624,1.000000

In [13]:
from sklearn.model_selection import train_test_split
X=df.loc[:, df.columns != 'Survived']
y=df ['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [14]:
from sklearn.linear_model import LogisticRegression
m1 = LogisticRegression()
m1.fit(X_train, y_train)

C:\Users\Tejas Patil\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [15]:
pred = m1.predict(X_test)
pred

array([1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0], dtype=int64)

In [16]:
m1.predict_proba(X_test)

array([[0.11756682, 0.88243318],
       [0.92139706, 0.07860294],
       [0.18104897, 0.81895103],
       [0.26514211, 0.73485789],
       [0.11512368, 0.88487632],
       [0.89131964, 0.10868036],
       [0.69547393, 0.30452607],
       [0.09846694, 0.90153306],
       [0.65121361, 0.34878639],
       [0.32986489, 0.67013511],
       [0.90623964, 0.09376036],
       [0.41350455, 0.58649545],
       [0.71539614, 0.28460386],
       [0.84215198, 0.15784802],
       [0.26504914, 0.73495086],
       [0.45590116, 0.54409884],
       [0.92004707, 0.07995293],
       [0.9268418 , 0.0731582 ],
       [0.93820593, 0.06179407],
       [0.30636432, 0.69363568],
       [0.92797421, 0.07202579],
       [0.88551775, 0.11448225],
       [0.02804659, 0.97195341],
       [0.78049177, 0.21950823],
       [0.25246213, 0.74753787],
       [0.91306252, 0.08693748],
       [0.05009779, 0.94990221],
       [0.38229626, 0.61770374],
       [0.82044763, 0.17955237],
       [0.12744807, 0.87255193],
       [0.37507094, 0.62492906],
       [0.47446382, 0.52553618],
       [0.54163576, 0.45836424],
       [0.47776384, 0.52223616],
       [0.88920892, 0.11079108],
       [0.47113412, 0.52886588],
       [0.5377427 , 0.4622573 ],
       [0.92134502, 0.07865498],
       [0.36903067, 0.63096933],
       [0.88727837, 0.11272163],
       [0.42349512, 0.57650488],
       [0.39090115, 0.60909885],
       [0.14283863, 0.85716137],
       [0.63274289, 0.36725711],
       [0.45341954, 0.54658046],
       [0.93571989, 0.06428011],
       [0.95732527, 0.04267473],
       [0.88656975, 0.11343025],
       [0.53377426, 0.46622574],
       [0.75191228, 0.24808772],
       [0.75088993, 0.24911007],
       [0.20668272, 0.79331728],
       [0.77416861, 0.22583139],
       [0.87324157, 0.12675843],
       [0.91943949, 0.08056051],
       [0.46996175, 0.53003825],
       [0.8378812 , 0.1621188 ],
       [0.76585524, 0.23414476],
       [0.94406888, 0.05593112],
       [0.35550777, 0.64449223],
       [0.89581912, 0.10418088],
       [0.86843284, 0.13156716],
       [0.82630811, 0.17369189],
       [0.82138313, 0.17861687],
       [0.52905124, 0.47094876],
       [0.28295714, 0.71704286],
       [0.84960331, 0.15039669],
       [0.85189499, 0.14810501],
       [0.08272598, 0.91727402],
       [0.92192099, 0.07807901],
       [0.94535074, 0.05464926],
       [0.95224722, 0.04775278],
       [0.51336703, 0.48663297],
       [0.92139706, 0.07860294],
       [0.29489101, 0.70510899],
       [0.80468532, 0.19531468],
       [0.22951404, 0.77048596],
       [0.83743425, 0.16256575],
       [0.61896888, 0.38103112],
       [0.03715383, 0.96284617],
       [0.9144694 , 0.0855306 ],
       [0.99192407, 0.00807593],
       [0.92141082, 0.07858918],
       [0.93316336, 0.06683664],
       [0.05535527, 0.94464473],
       [0.91943797, 0.08056203],
       [0.92141082, 0.07858918],
       [0.86843225, 0.13156775],
       [0.48133967, 0.51866033],
       [0.48551086, 0.51448914],
       [0.64611304, 0.35388696],
       [0.86864142, 0.13135858],
       [0.80943292, 0.19056708],
       [0.26504914, 0.73495086],
       [0.92154003, 0.07845997],
       [0.33922359, 0.66077641],
       [0.97500148, 0.02499852],
       [0.31605073, 0.68394927],
       [0.88311182, 0.11688818],
       [0.92139706, 0.07860294],
       [0.58422906, 0.41577094],
       [0.76953131, 0.23046869],
       [0.89369723, 0.10630277],
       [0.21200232, 0.78799768],
       [0.01920943, 0.98079057],
       [0.89917483, 0.10082517],
       [0.91930712, 0.08069288],
       [0.91929113, 0.08070887],
       [0.93734484, 0.06265516],
       [0.95108103, 0.04891897],
       [0.610821  , 0.389179  ],
       [0.82793875, 0.17206125],
       [0.91876342, 0.08123658],
       [0.92890309, 0.07109691],
       [0.80207251, 0.19792749],
       [0.93065855, 0.06934145],
       [0.87621073, 0.12378927],
       [0.56934999, 0.43065001],
       [0.39925199, 0.60074801],
       [0.46423877, 0.53576123],
       [0.32365624, 0.67634376],
       [0.75136039, 0.24863961],
       [0.92139706, 0.07860294],
       [0.76713037, 0.23286963],
       [0.06407205, 0.93592795],
       [0.03911886, 0.96088114],
       [0.25834709, 0.74165291],
       [0.37427984, 0.62572016],
       [0.99192407, 0.00807593],
       [0.83743425, 0.16256575],
       [0.9026926 , 0.0973074 ],
       [0.95472355, 0.04527645],
       [0.19590654, 0.80409346],
       [0.32528268, 0.67471732],
       [0.70104704, 0.29895296],
       [0.11607832, 0.88392168],
       [0.03488504, 0.96511496],
       [0.93702607, 0.06297393],
       [0.90729145, 0.09270855],
       [0.38387757, 0.61612243],
       [0.06643972, 0.93356028],
       [0.94600436, 0.05399564],
       [0.04175971, 0.95824029],
       [0.45079064, 0.54920936],
       [0.92138629, 0.07861371],
       [0.40993748, 0.59006252],
       [0.8487276 , 0.1512724 ],
       [0.92141082, 0.07858918],
       [0.27701674, 0.72298326],
       [0.89523794, 0.10476206],
       [0.19798254, 0.80201746],
       [0.96246225, 0.03753775],
       [0.84091899, 0.15908101],
       [0.20817315, 0.79182685],
       [0.92562406, 0.07437594],
       [0.92801022, 0.07198978],
       [0.89516333, 0.10483667],
       [0.95101724, 0.04898276],
       [0.2031834 , 0.7968166 ],
       [0.80207251, 0.19792749],
       [0.90818066, 0.09181934],
       [0.91634572, 0.08365428],
       [0.36468012, 0.63531988],
       [0.45863663, 0.54136337],
       [0.94851738, 0.05148262],
       [0.25635579, 0.74364421],
       [0.33895014, 0.66104986],
       [0.92562406, 0.07437594],
       [0.86980778, 0.13019222],
       [0.61041713, 0.38958287],
       [0.17958346, 0.82041654],
       [0.44055883, 0.55944117],
       [0.06416012, 0.93583988],
       [0.90142492, 0.09857508],
       [0.12189334, 0.87810666],
       [0.46510778, 0.53489222],
       [0.83743145, 0.16256855],
       [0.78280719, 0.21719281],
       [0.22485475, 0.77514525],
       [0.90563316, 0.09436684],
       [0.03591692, 0.96408308],
       [0.13991428, 0.86008572],
       [0.88024935, 0.11975065],
       [0.95245419, 0.04754581],
       [0.071268  , 0.928732  ],
       [0.76746022, 0.23253978],
       [0.92141082, 0.07858918],
       [0.04455103, 0.95544897],
       [0.83743425, 0.16256575],
       [0.06002025, 0.93997975],
       [0.48045538, 0.51954462],
       [0.62997174, 0.37002826],
       [0.26504914, 0.73495086],
       [0.20174119, 0.79825881],
       [0.20103041, 0.79896959],
       [0.04697274, 0.95302726],
       [0.84001203, 0.15998797],
       [0.19654047, 0.80345953],
       [0.90449725, 0.09550275],
       [0.88574001, 0.11425999],
       [0.87426155, 0.12573845],
       [0.23580069, 0.76419931],
       [0.86843225, 0.13156775],
       [0.69600161, 0.30399839],
       [0.61222915, 0.38777085],
       [0.09766266, 0.90233734],
       [0.17844945, 0.82155055],
       [0.81478508, 0.18521492],
       [0.71045093, 0.28954907],
       [0.96657155, 0.03342845],
       [0.03977177, 0.96022823],
       [0.92430734, 0.07569266],
       [0.86270531, 0.13729469],
       [0.75652529, 0.24347471],
       [0.88956913, 0.11043087],
       [0.93579392, 0.06420608],
       [0.83728469, 0.16271531],
       [0.03052745, 0.96947255],
       [0.27441644, 0.72558356],
       [0.87839807, 0.12160193],
       [0.47431028, 0.52568972],
       [0.86843225, 0.13156775],
       [0.69281651, 0.30718349],
       [0.8501112 , 0.1498888 ],
       [0.87548506, 0.12451494],
       [0.62019827, 0.37980173],
       [0.03235915, 0.96764085],
       [0.44717271, 0.55282729],
       [0.31340854, 0.68659146],
       [0.64871164, 0.35128836],
       [0.4453489 , 0.5546511 ],
       [0.81260585, 0.18739415],
       [0.64958115, 0.35041885],
       [0.86423259, 0.13576741],
       [0.94279844, 0.05720156],
       [0.38662408, 0.61337592],
       [0.4960005 , 0.5039995 ],
       [0.23886291, 0.76113709],
       [0.22493809, 0.77506191],
       [0.92027947, 0.07972053],
       [0.96016536, 0.03983464],
       [0.87336323, 0.12663677],
       [0.86983721, 0.13016279],
       [0.93187138, 0.06812862],
       [0.95208315, 0.04791685],
       [0.92518153, 0.07481847],
       [0.11698721, 0.88301279],
       [0.30826357, 0.69173643],
       [0.66357664, 0.33642336],
       [0.04423131, 0.95576869],
       [0.94904367, 0.05095633],
       [0.83348887, 0.16651113],
       [0.62657232, 0.37342768],
       [0.35498876, 0.64501124],
       [0.17981762, 0.82018238],
       [0.18221347, 0.81778653],
       [0.58399954, 0.41600046],
       [0.36388638, 0.63611362],
       [0.878263  , 0.121737  ],
       [0.4360481 , 0.5639519 ],
       [0.1503436 , 0.8496564 ],
       [0.87548506, 0.12451494],
       [0.26504914, 0.73495086],
       [0.20489384, 0.79510616],
       [0.8291375 , 0.1708625 ],
       [0.85923508, 0.14076492],
       [0.37930764, 0.62069236],
       [0.71224612, 0.28775388]])

In [17]:
from sklearn.metrics import confusion_matrix
labels = np.unique(y_test)
cm = confusion_matrix(y_test, pred, labels = labels)

In [18]:
cm

array([[128,  25],
       [ 32,  83]], dtype=int64)

In [19]:
from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.80      0.84      0.82       153
           1       0.77      0.72      0.74       115

    accuracy                           0.79       268
   macro avg       0.78      0.78      0.78       268
weighted avg       0.79      0.79      0.79       268

In [20]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, pred)
Precision = metrics.precision_score(y_test, pred)
Recall = metrics.recall_score(y_test, pred)
print("Accuracy :",accuracy)
print("Precision:",Precision)
print("Recall   :",Recall)

Accuracy : 0.7873134328358209
Precision: 0.7685185185185185
Recall   : 0.7217391304347827