In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Titanic.csv')
df.head()

,Pclass,Sex,Age,SibSp,Parch,family,Fare,Cabin,Embarked,Survived
0,3,male,22.0,1,0,1,7.2500,NaN,S,0
1,1,female,38.0,1,0,1,71.2833,C85,C,1
2,3,female,26.0,0,0,0,7.9250,NaN,S,1
3,1,female,35.0,1,0,1,53.1000,C123,S,1
4,3,male,35.0,0,0,0,8.0500,NaN,S,0

In [3]:
df['Age'].fillna (df['Age'].mean(), inplace=True)

In [4]:
df.head()

,Pclass,Sex,Age,SibSp,Parch,family,Fare,Cabin,Embarked,Survived
0,3,male,22.0,1,0,1,7.2500,NaN,S,0
1,1,female,38.0,1,0,1,71.2833,C85,C,1
2,3,female,26.0,0,0,0,7.9250,NaN,S,1
3,1,female,35.0,1,0,1,53.1000,C123,S,1
4,3,male,35.0,0,0,0,8.0500,NaN,S,0

In [5]:
df['Cabin'].fillna(0,inplace=True)

In [6]:
df.head()

,Pclass,Sex,Age,SibSp,Parch,family,Fare,Cabin,Embarked,Survived
0,3,male,22.0,1,0,1,7.2500,0,S,0
1,1,female,38.0,1,0,1,71.2833,C85,C,1
2,3,female,26.0,0,0,0,7.9250,0,S,1
3,1,female,35.0,1,0,1,53.1000,C123,S,1
4,3,male,35.0,0,0,0,8.0500,0,S,0

In [7]:
df['Cabin'] [df['Cabin'] !=0] = 1

In [8]:
df.head()

,Pclass,Sex,Age,SibSp,Parch,family,Fare,Cabin,Embarked,Survived
0,3,male,22.0,1,0,1,7.2500,0,S,0
1,1,female,38.0,1,0,1,71.2833,1,C,1
2,3,female,26.0,0,0,0,7.9250,0,S,1
3,1,female,35.0,1,0,1,53.1000,1,S,1
4,3,male,35.0,0,0,0,8.0500,0,S,0

In [9]:
df= pd.get_dummies(df, columns=['Sex', 'Embarked'], drop_first=True)

In [10]:
df.head()

,Pclass,Age,SibSp,Parch,family,Fare,Cabin,Survived,Sex_male,Embarked_N,Embarked_Q,Embarked_S
0,3,22.0,1,0,1,7.2500,0,0,True,False,False,True
1,1,38.0,1,0,1,71.2833,1,1,False,False,False,False
2,3,26.0,0,0,0,7.9250,0,1,False,False,False,True
3,1,35.0,1,0,1,53.1000,1,1,False,False,False,True
4,3,35.0,0,0,0,8.0500,0,0,True,False,False,True

In [11]:
df['Sex_male'] = df['Sex_male'].astype(int)
df['Embarked_N'] = df['Embarked_N'].astype (int)
df['Embarked_Q'] = df['Embarked_Q'].astype (int)
df['Embarked_S'] = df['Embarked_S'].astype (int)
df.head()

,Pclass,Age,SibSp,Parch,family,Fare,Cabin,Survived,Sex_male,Embarked_N,Embarked_Q,Embarked_S
0,3,22.0,1,0,1,7.2500,0,0,1,0,0,1
1,1,38.0,1,0,1,71.2833,1,1,0,0,0,0
2,3,26.0,0,0,0,7.9250,0,1,0,0,0,1
3,1,35.0,1,0,1,53.1000,1,1,0,0,0,1
4,3,35.0,0,0,0,8.0500,0,0,1,0,0,1

In [12]:
df.corr()

,Pclass,Age,SibSp,Parch,family,Fare,Cabin,Survived,Sex_male,Embarked_N,Embarked_Q,Embarked_S
Pclass,1.000000,-0.331339,0.083081,0.018443,0.065997,-0.549500,-0.725541,-0.338481,0.131900,-0.074282,0.221009,0.081720
Age,-0.331339,1.000000,-0.232625,-0.179191,-0.248512,0.091566,0.233123,-0.069809,0.084153,0.074099,-0.013855,-0.027121
SibSp,0.083081,-0.232625,1.000000,0.414838,0.890712,0.159651,-0.040460,-0.035322,-0.114631,-0.022508,-0.026354,0.070941
Parch,0.018443,-0.179191,0.414838,1.000000,0.783111,0.216225,0.036987,0.081629,-0.245489,-0.022467,-0.081228,0.063036
family,0.065997,-0.248512,0.890712,0.783111,1.000000,0.217138,-0.009175,0.016639,-0.200988,-0.026608,-0.058592,0.079977
Fare,-0.549500,0.091566,0.159651,0.216225,0.217138,1.000000,0.482075,0.257307,-0.182333,0.045646,-0.117216,-0.166603
Cabin,-0.725541,0.233123,-0.040460,0.036987,-0.009175,0.482075,1.000000,0.316912,-0.140391,0.087042,-0.129572,-0.110087
Survived,-0.338481,-0.069809,-0.035322,0.081629,0.016639,0.257307,0.316912,1.000000,-0.543351,0.060095,0.003650,-0.155660
Sex_male,0.131900,0.084153,-0.114631,-0.245489,-0.200988,-0.182333,-0.140391,-0.543351,1.000000,-0.064296,-0.074115,0.125722
Embarked_N,-0.074282,0.074099,-0.022508,-0.022467,-0.026608,0.045646,0.087042,0.060095,-0.064296,1.000000,-0.014588,-0.076588
Embarked_Q,0.221009,-0.013855,-0.026354,-0.081228,-0.058592,-0.117216,-0.129572,0.003650,-0.074115,-0.014588,1.000000,-0.496624
Embarked_S,0.081720,-0.027121,0.070941,0.063036,0.079977,-0.166603,-0.110087,-0.155660,0.125722,-0.076588,-0.496624,1.000000

In [13]:
from sklearn.model_selection import train_test_split
X=df.loc[:, df.columns != 'Survived']
y=df ['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [15]:
from sklearn.naive_bayes import GaussianNB
m2 = GaussianNB()
m2.fit(X, y)

GaussianNB()

In [16]:
pred = m2.predict(X_test)
pred

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0], dtype=int64)

In [17]:
m2.predict_proba(X_test)

array([[2.19176251e-01, 7.80823749e-01],
       [9.99469072e-01, 5.30927805e-04],
       [9.47127139e-01, 5.28728613e-02],
       [9.39094820e-01, 6.09051796e-02],
       [9.13949571e-01, 8.60504287e-02],
       [9.99390863e-01, 6.09137289e-04],
       [9.72162081e-01, 2.78379188e-02],
       [1.32543446e-01, 8.67456554e-01],
       [9.23502579e-01, 7.64974207e-02],
       [9.33312142e-01, 6.66878575e-02],
       [9.99434469e-01, 5.65531484e-04],
       [9.79280650e-01, 2.07193500e-02],
       [8.56123477e-01, 1.43876523e-01],
       [9.98840303e-01, 1.15969685e-03],
       [9.38978012e-01, 6.10219878e-02],
       [9.12212819e-01, 8.77871808e-02],
       [9.99999473e-01, 5.27173758e-07],
       [9.99366879e-01, 6.33121041e-04],
       [9.99492029e-01, 5.07970710e-04],
       [9.99585130e-01, 4.14869964e-04],
       [9.99480453e-01, 5.19547139e-04],
       [9.98291323e-01, 1.70867722e-03],
       [5.68605133e-02, 9.43139487e-01],
       [9.94419525e-01, 5.58047477e-03],
       [9.22952555e-01, 7.70474445e-02],
       [9.99453295e-01, 5.46705406e-04],
       [5.74144352e-11, 1.00000000e+00],
       [9.59475420e-01, 4.05245801e-02],
       [9.98777002e-01, 1.22299782e-03],
       [3.29195543e-03, 9.96708045e-01],
       [9.78061997e-01, 2.19380027e-02],
       [9.10302981e-01, 8.96970186e-02],
       [9.99957198e-01, 4.28018870e-05],
       [9.76501857e-01, 2.34981430e-02],
       [9.98371013e-01, 1.62898705e-03],
       [9.99999946e-01, 5.41773560e-08],
       [9.17397512e-01, 8.26024884e-02],
       [9.99467356e-01, 5.32643529e-04],
       [6.35169917e-01, 3.64830083e-01],
       [9.99377667e-01, 6.22333388e-04],
       [9.79571547e-01, 2.04284533e-02],
       [9.76364441e-01, 2.36355590e-02],
       [1.33661080e-01, 8.66338920e-01],
       [9.14050528e-01, 8.59494718e-02],
       [9.89887269e-01, 1.01127306e-02],
       [9.99487597e-01, 5.12402576e-04],
       [1.00000000e+00, 5.50501750e-13],
       [9.98895680e-01, 1.10432015e-03],
       [1.21608127e-42, 1.00000000e+00],
       [9.98493732e-01, 1.50626819e-03],
       [9.96770614e-01, 3.22938593e-03],
       [9.51585683e-01, 4.84143175e-02],
       [9.98602208e-01, 1.39779186e-03],
       [9.98884149e-01, 1.11585074e-03],
       [9.99468926e-01, 5.31073757e-04],
       [9.76507451e-01, 2.34925486e-02],
       [9.98824671e-01, 1.17532920e-03],
       [8.86529719e-01, 1.13470281e-01],
       [9.99998873e-01, 1.12686126e-06],
       [9.76983973e-01, 2.30160266e-02],
       [1.00000000e+00, 2.65270643e-26],
       [9.98512987e-01, 1.48701277e-03],
       [9.98004767e-01, 1.99523309e-03],
       [9.95620941e-01, 4.37905886e-03],
       [8.43578228e-01, 1.56421772e-01],
       [9.38422489e-01, 6.15775111e-02],
       [9.98133625e-01, 1.86637493e-03],
       [9.98463180e-01, 1.53681991e-03],
       [4.35399936e-01, 5.64600064e-01],
       [9.98713988e-01, 1.28601231e-03],
       [9.99879456e-01, 1.20544393e-04],
       [9.99999992e-01, 7.91375277e-09],
       [4.40177595e-01, 5.59822405e-01],
       [9.99469072e-01, 5.30927805e-04],
       [4.83408880e-01, 5.16591120e-01],
       [9.95751649e-01, 4.24835146e-03],
       [7.67294958e-01, 2.32705042e-01],
       [9.98292039e-01, 1.70796108e-03],
       [7.56755284e-01, 2.43244716e-01],
       [2.87537866e-02, 9.71246213e-01],
       [9.98905877e-01, 1.09412270e-03],
       [1.00000000e+00, 6.98358820e-28],
       [9.99469501e-01, 5.30499002e-04],
       [9.99483214e-01, 5.16785748e-04],
       [2.60807288e-01, 7.39192712e-01],
       [9.99468890e-01, 5.31109584e-04],
       [9.99469501e-01, 5.30499002e-04],
       [9.98512951e-01, 1.48704914e-03],
       [9.99999948e-01, 5.20292833e-08],
       [9.99723264e-01, 2.76736295e-04],
       [9.15275795e-01, 8.47242049e-02],
       [9.98524492e-01, 1.47550762e-03],
       [9.98180779e-01, 1.81922101e-03],
       [9.38978012e-01, 6.10219878e-02],
       [9.99473032e-01, 5.26967850e-04],
       [7.90002363e-01, 2.09997637e-01],
       [9.99357044e-01, 6.42955816e-04],
       [9.46459290e-01, 5.35407098e-02],
       [9.99363583e-01, 6.36417119e-04],
       [9.99469072e-01, 5.30927805e-04],
       [9.84958936e-01, 1.50410636e-02],
       [9.95593500e-01, 4.40650007e-03],
       [9.98407662e-01, 1.59233772e-03],
       [9.08703229e-01, 9.12967712e-02],
       [2.56328816e-02, 9.74367118e-01],
       [9.99418208e-01, 5.81791658e-04],
       [9.99465368e-01, 5.34632407e-04],
       [9.99464876e-01, 5.35123637e-04],
       [9.99999990e-01, 9.97910476e-09],
       [9.99493468e-01, 5.06531840e-04],
       [6.35906633e-01, 3.64093367e-01],
       [9.98328733e-01, 1.67126695e-03],
       [9.98840510e-01, 1.15948950e-03],
       [9.99366389e-01, 6.33610687e-04],
       [9.98721193e-01, 1.27880694e-03],
       [9.99483882e-01, 5.16117624e-04],
       [9.98671556e-01, 1.32844425e-03],
       [8.53730691e-01, 1.46269309e-01],
       [9.52666432e-01, 4.73335681e-02],
       [9.80545430e-01, 1.94545700e-02],
       [9.49691082e-01, 5.03089181e-02],
       [6.46268761e-01, 3.53731239e-01],
       [9.99469072e-01, 5.30927805e-04],
       [9.98572682e-01, 1.42731785e-03],
       [3.37698225e-05, 9.99966230e-01],
       [1.83173149e-01, 8.16826851e-01],
       [9.56949759e-01, 4.30502411e-02],
       [9.77806709e-01, 2.21932910e-02],
       [1.00000000e+00, 6.98358820e-28],
       [9.98292039e-01, 1.70796108e-03],
       [9.99424909e-01, 5.75091485e-04],
       [9.99486661e-01, 5.13339317e-04],
       [9.83768496e-01, 1.62315039e-02],
       [4.57853682e-01, 5.42146318e-01],
       [9.99880516e-01, 1.19484284e-04],
       [9.21223381e-05, 9.99907878e-01],
       [3.69748362e-02, 9.63025164e-01],
       [1.00000000e+00, 8.08088630e-13],
       [9.99264297e-01, 7.35703329e-04],
       [9.78191300e-01, 2.18087001e-02],
       [2.90106380e-04, 9.99709894e-01],
       [9.99485134e-01, 5.14866362e-04],
       [4.62883614e-03, 9.95371164e-01],
       [9.80236830e-01, 1.97631701e-02],
       [9.99468729e-01, 5.31270944e-04],
       [9.73369451e-01, 2.66305492e-02],
       [9.98848717e-01, 1.15128296e-03],
       [9.99469501e-01, 5.30499002e-04],
       [9.99051500e-01, 9.48499786e-04],
       [9.99403215e-01, 5.96785313e-04],
       [9.41780615e-01, 5.82193848e-02],
       [9.99426251e-01, 5.73748847e-04],
       [9.99999967e-01, 3.32682973e-08],
       [9.31919812e-01, 6.80801881e-02],
       [9.98956653e-01, 1.04334687e-03],
       [9.99481612e-01, 5.18388099e-04],
       [9.99401070e-01, 5.98930281e-04],
       [9.99490566e-01, 5.09433502e-04],
       [8.75302267e-01, 1.24697733e-01],
       [9.98721193e-01, 1.27880694e-03],
       [9.98697267e-01, 1.30273299e-03],
       [9.99462465e-01, 5.37535301e-04],
       [9.77347314e-01, 2.26526863e-02],
       [9.02449266e-01, 9.75507341e-02],
       [9.99885844e-01, 1.14155775e-04],
       [9.23947946e-01, 7.60520542e-02],
       [9.93307053e-01, 6.69294718e-03],
       [9.98956653e-01, 1.04334687e-03],
       [9.99314707e-01, 6.85293330e-04],
       [5.80748469e-02, 9.41925153e-01],
       [6.68441946e-43, 1.00000000e+00],
       [9.99999939e-01, 6.12331567e-08],
       [3.69528200e-02, 9.63047180e-01],
       [9.99286877e-01, 7.13122743e-04],
       [2.17254698e-01, 7.82745302e-01],
       [9.11568931e-01, 8.84310688e-02],
       [9.98291884e-01, 1.70811557e-03],
       [9.98041039e-01, 1.95896058e-03],
       [9.86387814e-01, 1.36121856e-02],
       [9.99644264e-01, 3.55735658e-04],
       [4.96324060e-02, 9.50367594e-01],
       [5.27988708e-01, 4.72011292e-01],
       [9.98922401e-01, 1.07759923e-03],
       [9.98482206e-01, 1.51779385e-03],
       [6.62427101e-08, 9.99999934e-01],
       [9.98576654e-01, 1.42334564e-03],
       [9.99469501e-01, 5.30499002e-04],
       [5.36485685e-11, 1.00000000e+00],
       [9.98292039e-01, 1.70796108e-03],
       [9.26617850e-02, 9.07338215e-01],
       [8.72348669e-01, 1.27651331e-01],
       [9.06494646e-01, 9.35053542e-02],
       [9.38978012e-01, 6.10219878e-02],
       [9.30138285e-01, 6.98617145e-02],
       [9.11496872e-01, 8.85031279e-02],
       [0.00000000e+00, 1.00000000e+00],
       [9.98739698e-01, 1.26030244e-03],
       [9.47328759e-01, 5.26712413e-02],
       [9.99430252e-01, 5.69747732e-04],
       [9.67479790e-01, 3.25202099e-02],
       [9.99328929e-01, 6.71070530e-04],
       [4.39257972e-01, 5.60742028e-01],
       [9.98512951e-01, 1.48704914e-03],
       [9.96439693e-01, 3.56030659e-03],
       [8.58747282e-01, 1.41252718e-01],
       [5.00638215e-01, 4.99361785e-01],
       [4.94029907e-02, 9.50597009e-01],
       [9.98764770e-01, 1.23523045e-03],
       [9.95501809e-01, 4.49819067e-03],
       [9.99895759e-01, 1.04240782e-04],
       [2.34284099e-02, 9.76571590e-01],
       [9.99999999e-01, 1.48249088e-09],
       [9.98492552e-01, 1.50744813e-03],
       [9.97805873e-01, 2.19412729e-03],
       [9.98663726e-01, 1.33627399e-03],
       [9.99490446e-01, 5.09554334e-04],
       [9.98283242e-01, 1.71675832e-03],
       [2.22503254e-03, 9.97774967e-01],
       [9.49687920e-01, 5.03120798e-02],
       [9.94917880e-01, 5.08211984e-03],
       [9.10806815e-01, 8.91931853e-02],
       [9.98512951e-01, 1.48704914e-03],
       [9.05975338e-01, 9.40246623e-02],
       [9.92101983e-01, 7.89801681e-03],
       [9.98122443e-01, 1.87755688e-03],
       [2.83231124e-01, 7.16768876e-01],
       [7.73821562e-03, 9.92261784e-01],
       [8.23013123e-01, 1.76986877e-01],
       [9.50727508e-01, 4.92724923e-02],
       [5.26279879e-01, 4.73720121e-01],
       [9.44536984e-01, 5.54630156e-02],
       [9.97626703e-01, 2.37329711e-03],
       [9.95090119e-01, 4.90988122e-03],
       [9.98880383e-01, 1.11961748e-03],
       [9.99494228e-01, 5.05771592e-04],
       [9.41624393e-01, 5.83756065e-02],
       [9.88375364e-01, 1.16246358e-02],
       [9.29010175e-01, 7.09898252e-02],
       [6.49557153e-02, 9.35044285e-01],
       [9.99329406e-01, 6.70594018e-04],
       [9.98018997e-01, 1.98100333e-03],
       [9.99829429e-01, 1.70571233e-04],
       [9.98517645e-01, 1.48235508e-03],
       [9.98978849e-01, 1.02115112e-03],
       [9.99253990e-01, 7.46009648e-04],
       [9.99475970e-01, 5.24029767e-04],
       [5.17266840e-01, 4.82733160e-01],
       [9.59162518e-01, 4.08374817e-02],
       [9.96248672e-01, 3.75132834e-03],
       [8.83280206e-03, 9.91167198e-01],
       [9.99490895e-01, 5.09105289e-04],
       [9.98278747e-01, 1.72125293e-03],
       [6.71828125e-01, 3.28171875e-01],
       [1.38716032e-01, 8.61283968e-01],
       [8.27934739e-05, 9.99917207e-01],
       [9.25712987e-01, 7.42870128e-02],
       [6.49235819e-01, 3.50764181e-01],
       [9.59688750e-01, 4.03112501e-02],
       [9.98680098e-01, 1.31990159e-03],
       [9.99979277e-01, 2.07228713e-05],
       [9.15324803e-01, 8.46751969e-02],
       [9.98122443e-01, 1.87755688e-03],
       [9.38978012e-01, 6.10219878e-02],
       [9.46865886e-01, 5.31341135e-02],
       [9.98739473e-01, 1.26052660e-03],
       [9.98872092e-01, 1.12790803e-03],
       [2.50026877e-01, 7.49973123e-01],
       [8.12425155e-01, 1.87574845e-01]])

In [18]:
from sklearn.metrics import confusion_matrix
labels = np.unique(y_test)
cm = confusion_matrix(y_test, pred, labels = labels)

In [19]:
cm

array([[148,   5],
       [ 80,  35]], dtype=int64)

In [20]:
from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.65      0.97      0.78       153
           1       0.88      0.30      0.45       115

    accuracy                           0.68       268
   macro avg       0.76      0.64      0.61       268
weighted avg       0.75      0.68      0.64       268

In [21]:
from sklearn import metrics
accuracy = metrics.accuracy_score(y_test, pred)
Precision = metrics.precision_score(y_test, pred)
Recall = metrics.recall_score(y_test, pred)
print("Accuracy :",accuracy)
print("Precision:",Precision)
print("Recall   :",Recall)

Accuracy : 0.6828358208955224
Precision: 0.875
Recall   : 0.30434782608695654